loglevel: info
environment: dev

twitch:
  clientid: "${client_id}"
  clientsecret: "${client_secret}"
  redirecturi: "${redirect_uri}"
  state: ""

kube:
  namespace: ${namespace}
  oauthsecret: ${oauth_secret}

http:
  port: ${port}

health:
  enabled: false
  port: 0

prometheus:
  enabled: false
  port: 0
