loglevel: info

ratelimit:
  join: 20
  auth: 20
  reset: 10s
  redis:
    username: default
    password: password
    database: 1
    sentinel: false
    addresses:
      - 0.0.0.0:6379
    master: ""

twitch:
  user: justinfan77777
  oauth: oauth

nats:
  url: 0.0.0.0:4222
  stream: twitchIRC
  topic:
    raw: irc.raw.twitch
    api: irc.api.twitch

mongo:
  connectionstring: mongodb://username:password@0.0.0.0:27017
  database: irc-reader
  collection: twitch-irc-channels
  username: ""
  password: ""

health:
  enabled: false
  port: 0

prometheus:
  enabled: false
  port: 0
